/// <reference types="astro/client" />

// Env is declared in worker-configuration.d.ts (auto-generated by `wrangler types`).
// Do NOT manually define it here — running `wrangler types` keeps it in sync with wrangler.jsonc.
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
	interface Locals extends Runtime {
		user: import('better-auth').User | null;
		session: import('better-auth').Session | null;
	}
}
